### ISSUE TITLE
Wasabi wallet update

### ISSUE THREAD

**Issue by Sami32** [thebitcoinhole/software-wallets#420]
It now support Silent Payments sending:

https://github.com/WalletWasabi/WalletWasabi/pull/13536
https://github.com/WalletWasabi/WalletWasabi/releases

**Comment by maxirosson** [comment]
This is a WIP, not available yet.

**Comment by Sami32** [comment]
Yep, it will be in the next release that is few weeks away, so as long as you can remember it it is fine.

**Comment by maxirosson** [comment]
Yes, I read all the release notes, so I will include this as soon as they release it. Thanks
